### PR TITLE
Tractometry refactor to minimize number of files

### PR DESCRIPTION
**Pull request by frheault**
To allow smoother use on clusters major changes had to be done.
Every process is now grouped by bundle and for loop in bash are now required to keep scilpy script simple and easy to use outside of the pipeline while producing the same output.

All subject-wise aggregate are now gone, jq is not used anymore. It was impossible to read and modify, so scil_merge_json.py was updated to replace it.

Pruning and outliers removals are now gone, input metrics don't have to be rename anymore (no need to cut out _subj___) and a parameter was added to easily remove __m_cleaned_ from rbx_flow pipeline.

### CODE REVIEW

**Comment by frheault** [comment]
@mdesco faudrait du testing, mais je pense que ca va etre bon

**Comment by mdesco** [comment]
Ok. On my todo list. I will test. Anything in particular I should pay attention to?
Maybe a call or an update to the lab, in a lab meeting could be good.

**Comment by frheault** [comment]
I should work just like before, you can try it without my input (don't forget you need the PR branch from scilpy at the same time) and then we could talk about optim for clusters or the differences in the code.

**Review by mdesco — COMMENTED** [review]
Sorry. I just posted a comment on the scilpy PR360 that comes with this.
Minor problem with  plots with n_pts = 100

**Review by mdesco — COMMENTED** [review]
The main.nf is not up-to-date with the scilpy-latest.sif build from @arnaudbore 
Options to scil_compute_bundle_voxel_label_map have changed...

Command error:
  usage: scil_compute_bundle_voxel_label_map.py [-h] [--upsample UPSAMPLE]
                                                [--reference REFERENCE] [-f]
                                                [-v]
                                                in_bundle in_centroid out_map
  scil_compute_bundle_voxel_label_map.py: error: unrecognized arguments: --out_labels_npz 102311__AF_L_labels.npz --out_distances_npz 102311__AF_L_distances.npz --labels_color_dpp 102311__AF_L_labels.trk --distances_color_dpp 102311__AF_L_distances.trk

**Comment by frheault** [comment]
@arnaudbore @mdesco It is the other way around, the .sif is not up to date.
The scil_compute_bundle_voxel_label_map.py changed in the latest PR (#362 I think, improve label map)

**Comment by arnaudbore** [comment]
> @arnaudbore @mdesco It is the other way around, the .sif is not up to date.
> The scil_compute_bundle_voxel_label_map.py changed in the latest PR (#362 I think, improve label map)

dockerhub has been updated

**Review by mdesco — COMMENTED** [review]
Everything works now.

@frheault sometimes plots of MD, AD, ... such metrics do not show std in the visu... Is it because STD is too small? Or it hides a bug. It often shows something but sometimes disappear...

IFOF_L_md_metric
UF_R_ad_metric
CST_R_rd_metric

**Comment by frheault** [comment]
@mdesco Is it at the population level? Or the individual level?
How many people, do the bundle look normal?
Worst case, send me the data

**Comment by mdesco** [comment]
Population level. Same data as last time… Do you still have it?

**Pull request merged**
