### PR TITLE
harmonize_json

### PR DESCRIPTION
**Pull request by frheault**
Simplify handling of missing data in the JSON for tractometry analysis.

### CODE REVIEW

**Comment by frheault** [comment]
@arnaudbore I think this is now an important PR as it solves a big problem.

When computing fixel stuff, 1) it was taking distance and label map as metrics and since each bundle has one, it was computing like 100 metrics more per bundle by accident.
2) The json/xlsx were broken since the afd_metric had a unique name per bundle rather than an uniformed name.

This PR fixes this as well as making sure the json/xlsx are well constructed for analysis. (we should have a call about this, its hard to explain)

I think someone should test this with
2-3 subjects, not the exact same bundle and metric for each subject and carefully examine the plot and json/xlsx and we should have a call about it.

I think this has been <broken> for some time.

**Comment by frheault** [comment]
@Manonedde maybe you could test this PR (can be used with scilpy master) and investigate the output in depth to see if everything that has to disappear is gone?

**Comment by Manonedde** [comment]
No problem, I'll look at it next week.

**Comment by Manonedde** [comment]
I tested on 10 subjects, 2 bundles and 4 metrics (DTI + AFD fixel).
The 2 problems mentioned above for the fixel stuff are solved. The json and excel no longer contain labels and distances; and afd_metric had a uniform name.

**Comment by Manonedde** [comment]
@arnaudbore @frheault 
I tested on 10 subjects, 2 bundles and 4 metrics (DTI + AFD fixel).
The 2 problems mentioned above for the fixel stuff are solved. The json and excel no longer contain labels and distances; and afd_metric had a uniform name.

**Pull request merged**
